<a href="https://colab.research.google.com/github/Rakib911Hossan/Al_Project/blob/main/44_2_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as n
from sklearn import preprocessing
data=n.array([[12,-9,0.5],
                 [34,-7,1],
                 [3.6,11,32]])


In [ ]:
binary_data=preprocessing.Binarizer(threshold=10).transform(data)
print(binary_data)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 1.]]


In [ ]:
max_min_data=preprocessing.MinMaxScaler(feature_range=(10,12)).fit_transform(data)
print(max_min_data)

[[10.55263158 10.         10.        ]
 [12.         10.2        10.03174603]
 [10.         12.         12.        ]]


In [ ]:
normalize_data=preprocessing.normalize(data,norm='l1')
print(normalize_data)

normalize_data=preprocessing.normalize(data,norm='l2')
print(normalize_data)

[[ 0.55813953 -0.41860465  0.02325581]
 [ 0.80952381 -0.16666667  0.02380952]
 [ 0.07725322  0.2360515   0.68669528]]
[[ 0.79955593 -0.59966694  0.03331483]
 [ 0.97905088 -0.2015693   0.02879561]
 [ 0.10579271  0.32325549  0.9403796 ]]
