<a href="https://colab.research.google.com/github/Rakib911Hossan/Al_Project/blob/main/data_process_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn import preprocessing

data = np.array([[12, -9, 0.5],
                 [34, -7, 1],
                 [3.6, 11, 32]])

standardized_data = preprocessing.StandardScaler().fit_transform(data)
print("Standardized Data:\n", standardized_data)


Standardized Data:
 [[-0.35366814 -0.81537425 -0.72400784]
 [ 1.36266253 -0.59299945 -0.69006997]
 [-1.00899439  1.4083737   1.41407782]]


In [4]:
robust_scaled_data = preprocessing.RobustScaler().fit_transform(data)
print("Robust Scaled Data:\n", robust_scaled_data)


Robust Scaled Data:
 [[ 0.         -0.2        -0.03174603]
 [ 1.44736842  0.          0.        ]
 [-0.55263158  1.8         1.96825397]]


In [6]:
quantile_transformed_data = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(data)
print("Quantile Transformed Data (Uniform):\n", quantile_transformed_data)


Quantile Transformed Data (Uniform):
 [[0.5 0.  0. ]
 [1.  0.5 0.5]
 [0.  1.  1. ]]


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_data.py:2829: UserWarning: n_quantiles (1000) is greater than the total number of samples (3). n_quantiles is set to n_samples.
  warnings.warn(


In [9]:
quantile_transformed_gaussian = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(data)
print("Quantile Transformed Data (Gaussian):\n", quantile_transformed_gaussian)

Quantile Transformed Data (Gaussian):
 [[ 0.         -5.19933758 -5.19933758]
 [ 5.19933758  0.          0.        ]
 [-5.19933758  5.19933758  5.19933758]]


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_data.py:2829: UserWarning: n_quantiles (1000) is greater than the total number of samples (3). n_quantiles is set to n_samples.
  warnings.warn(


In [10]:
power_transformed_data = preprocessing.PowerTransformer(method='yeo-johnson').fit_transform(data)
print("Power Transformed Data:\n", power_transformed_data)


Power Transformed Data:
 [[ 0.00780855 -0.91786524 -0.92211085]
 [ 1.22082193 -0.47280906 -0.46753689]
 [-1.22863048  1.3906743   1.38964774]]


In [11]:
max_abs_scaled_data = preprocessing.MaxAbsScaler().fit_transform(data)
print("Max Abs Scaled Data:\n", max_abs_scaled_data)


Max Abs Scaled Data:
 [[ 0.35294118 -0.81818182  0.015625  ]
 [ 1.         -0.63636364  0.03125   ]
 [ 0.10588235  1.          1.        ]]
