<a href="https://colab.research.google.com/github/Rakib911Hossan/Al_Project/blob/main/data_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as n
from sklearn import preprocessing

data = n.array([[12, -9,0.5],
 [34,-7,1],
  [3.6,11,32]])

binary_data = preprocessing.Binarizer(threshold=10).transform(data)
print(binary_data)


[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 1.]]


In [9]:
import numpy as n
from sklearn import preprocessing

data = n.array([[12, -9,0.5],
 [34,-7,1],
  [3.6,11,32]])

min_max_scaler = preprocessing.MinMaxScaler(feature_range=(12,10)).transform(data)
print(binary_data)


NotFittedError: This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.