<a href="https://colab.research.google.com/github/Rakib911Hossan/Al_Project/blob/main/data_process_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn import preprocessing

data = np.array([[12, -9, 0.5],
                 [34, -7, 1],
                 [3.6, 11, 32]])

scaler = preprocessing.StandardScaler()
standardized_data = scaler.fit_transform(data)
print("Standardized Data:\n", standardized_data)


Standardized Data:
 [[-0.35366814 -0.81537425 -0.72400784]
 [ 1.36266253 -0.59299945 -0.69006997]
 [-1.00899439  1.4083737   1.41407782]]


In [3]:
robust_scaler = preprocessing.RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(data)
print("Robust Scaled Data:\n", robust_scaled_data)


Robust Scaled Data:
 [[ 0.         -0.2        -0.03174603]
 [ 1.44736842  0.          0.        ]
 [-0.55263158  1.8         1.96825397]]
